apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app-deployment
  template:
    metadata:
      labels:
        app: express-app-deployment
    spec:
      containers:
      - name: express-app-deployment
        image: dmytrobetterme/dmytro-soroka-express-app:2
        ports:
        - containerPort: 3000

