apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-mongodb
        env:
          - name: MONGO_USER
            value: 'root'
          - name: MONGO_HOST
            value: '{{ .Release.Name }}-mongodb'
          - name: MONGO_PORT
            value: '27017'
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodb
                key: mongodb-root-password
          - name: MONGO_URL
            value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)"